export const ADD_PAINTING_CATEGORY = 'ADD_PAINTING_CATEGORY';

export const REMOVE_PAINTING_CATEGORY = 'REMOVE_PAINTING_CATEGORY';

export const ADD_MOVIE = 'ADD_MOVIE';

export const REMOVE_MOVIE = 'REMOVE_MOVIE';
